perfomancereview/perfomancereview/urls.py
from django.contrib import admin
from django.urls import path

from accounts import views as accounts_views
from employee import views

urlpatterns = [
    path("login/", accounts_views.login, name='login'),
    path("logout/", accounts_views.logout, name='logout'),
    path('create-employee', views.create_employee, name='create-employee'),
    path('employees', views.employees, name='employees'),
    path('edit-employee/<str:id>', views.edit_employee, name='edit-employee'),
    path('update-employee/<str:id>', views.update_employee),
    path('delete-employee/<str:id>', views.delete_employee, name='delete-employee'),
    path('', views.employees, name='employees'),
]

perfomancereview/accounts/models.py
from django.db import models

# Create your models here.

perfomancereview/employee/models.py
from django.db import models


class Employee(models.Model):
    id = models.CharField(max_length=20, primary_key=True)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    contact = models.CharField(max_length=15)

    class Meta:
        db_table = "employee"

perfomancereview/employee/forms.py
from django import forms
from employee.models import Employee


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = "__all__"
        exclude = ['id']

perfomancereview/accounts/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib import auth
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import logout as auth_logout

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('employees')
        else:
            messages.info(request, "Wrong username or password")
            return redirect('login')
    else:
        return render(request, 'registration/login.html')

def logout(request):
    auth_logout(request)
    return redirect('login')

perfomancereview/employee/views.py
import uuid;

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from employee.forms import EmployeeForm
from employee.models import Employee


@login_required
# Create your views here.
def create_employee(request):
    if request.method == "POST":
        form = EmployeeForm(request.POST)
        if form.is_valid():
            try:
                employee = Employee(
                    id=str(uuid.uuid4()),
                    name=form.cleaned_data['name'],
                    email=form.cleaned_data['email'],
                    contact=form.cleaned_data['contact'],
                )
                employee.save()

                user = User.objects.create_user(
                    username=employee.email,  # Or any suitable username based on employee data
                    email=employee.email,
                    password='abcd@1234',
                    is_staff=True,
                )
                user.save()

                # Optionally, link the employee instance to the user

                return redirect("/employees")
            except:
                pass
    else:
        form = EmployeeForm()
    return render(request, 'create-employee.html', {'form': form})


@login_required
def employees(request):
    employees = Employee.objects.all()
    return render(request, "employees.html", {'employees': employees})


@login_required
def edit_employee(request, id):
    employee = Employee.objects.get(id=id)
    return render(request, 'edit-employee.html', {'employee': employee})


@login_required
def update_employee(request, id):
    employee = Employee.objects.get(id=id)
    form = EmployeeForm(request.POST, instance=employee)
    if form.is_valid():
        employee.name = form.cleaned_data['name']
        employee.email = form.cleaned_data['email']
        employee.contact = form.cleaned_data['contact']
        employee.save()
        return redirect("/employees")
    return render(request, 'edit-employee.html', {'employee': employee})


@login_required
def delete_employee(request, id):
    employee = Employee.objects.get(id=id)
    employee.delete()
    return redirect("/employees")

perfomancereview/employee/templates/create-employee.html
{% extends "base.html" %}

{% load static %}

{% block pagetitle %}
    {% include "page-title.html" with title="Create Employee" %}
{% endblock pagetitle %}

{% block content %}


    <form class="max-w-fit mx-auto" method="POST" action="/create-employee">
        {% if form.errors %}
            <div>
                {% for field in form %}
                    {% for error in field.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                {% endfor %}
            </div>
        {% endif %}
        {% csrf_token %}
        <div class="relative z-0 w-full mb-5 group">
            <input name="name" id="id_name" required maxlength="100"
                   class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                   placeholder=" " required/>
            <label for="floating_email"
                   class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Employee
                Name</label>
        </div>
        <div class="relative z-0 w-full mb-5 group">
            <input type="email" name="email" id="id_email" required maxlength="254"
                   class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                   placeholder=" " required/>
            <label for="floating_password"
                   class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Email</label>
        </div>
        <div class="relative z-0 w-full mb-5 group">
            <input type="tel" pattern="0[1-9]{9}" name="contact" id="id_contact" required maxlength="15"
                   class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                   placeholder=" " required/>
            <label for="floating_repeat_password"
                   class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Contact</label>
        </div>
        <button type="submit"
                class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
            Submit
        </button>
    </form>

{% endblock content %}

perfomancereview/employee/templates/edit-employee.html
{% extends "base.html" %}

{% load static %}

{% block pagetitle %}
    {% include "page-title.html" with title="Create Employee" %}
{% endblock pagetitle %}

{% block content %}


    <form class="max-w-fit mx-auto" method="POST" action="/update-employee/{{employee.id}}">
        {% if form.errors %}
            <div>
                {% for field in form %}
                    {% for error in field.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                {% endfor %}
            </div>
        {% endif %}
        {% csrf_token %}
        <div class="relative z-0 w-full mb-5 group">
            <input value="{{ employee.name }}" name="name" id="id_name" required maxlength="100"
                   class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                   placeholder=" " required/>
            <label for="name"
                   class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Employee
                Name</label>
        </div>
        <div class="relative z-0 w-full mb-5 group">
            <input value="{{ employee.email }}" type="email" name="email" id="id_email" required maxlength="254"
                   class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                   placeholder=" " required/>
            <label for="email"
                   class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Email</label>
        </div>
        <div class="relative z-0 w-full mb-5 group">
            <input value="{{ employee.contact }}" type="tel" pattern="0[1-9]{9}" name="contact" id="id_contact" required maxlength="15"
                   class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                   placeholder=" " required/>
            <label for="contact"
                   class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Contact</label>
        </div>
        <button type="submit"
                class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
            Submit
        </button>
    </form>

{% endblock content %}

perfomancereview/employee/templates/employees.html
{% extends "base.html" %}

{% load static %}
{% block title %}Show all{% endblock title %}

{% block pagetitle %}
    {% include "page-title.html" with title="Show all Employee" %}
    <button onclick="window.location.href='{% url 'create-employee' %}';" type="button"
            class="focus:outline-none text-white bg-purple-700 hover:bg-purple-800 focus:ring-4 focus:ring-purple-300 font-medium rounded-lg text-sm px-5 py-2.5 mb-2 dark:bg-purple-600 dark:hover:bg-purple-700 dark:focus:ring-purple-900">
        Create employee
    </button>
{% endblock pagetitle %}

{% block content %}
    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
        <tr>
            <th scope="col" class="px-6 py-3">
                Name
            </th>
            <th scope="col" class="px-6 py-3">
                Email
            </th>
            <th scope="col" class="px-6 py-3">
                Contact
            </th>
            <th scope="col" class="px-6 py-3">
                Action
            </th>
        </tr>
        </thead>
        <tbody>
        {% for employee in employees %}
            <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                <td class="px-6 py-4">
                    {{ employee.name }}
                </td>
                <td class="px-6 py-4">
                    {{ employee.email }}
                </td>
                <td class="px-6 py-4">
                    {{ employee.contact }}
                </td>
                <td class="flex items-center px-6 py-4">
                    <a href="{% url 'edit-employee'  id=employee.id %}"
                       class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Edit
                    </a>
                    <a href="{% url 'delete-employee'  id=employee.id %}" class="font-medium text-red-600 dark:text-red-500 hover:underline ms-3">Remove</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}